version: '3'
services:
  nginx:
    image: nginx:latest
    links:
    - app:uwsgi
    volumes:
    - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/snippets:/etc/nginx/snippets
    - ./nginx/cert:/cert
    - ./static:/static
    ports:
    - 80:80
    - 443:443

  worker:
    image: service-app
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: python worker.py
    depends_on:
    - rabbitmq
    env_file:
    - .env
    volumes:
    - .:/app


  app:
    image: service-app
    ports:
      - "8000:8000"
    entrypoint: sh app-entrypoint.sh
    depends_on:
      - db
      - worker
    env_file:
    - .env
    volumes:
    - .:/app

  db:
    image: "postgres"

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
    - "15672:15672"
    - "5672:5672"
    labels:
      NAME: "rabbitmq"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 5s
      timeout: 10s
      retries: 5